# @name createPerson

POST http://localhost:5000/api/persons
Content-Type: application/json

{
    "name": "Jim juju",
    "age": 30
}

###

# @name getPerson
GET http://localhost:5000/api/persons/{{createPerson.response.body.$.id}}
Content-Type: application/json

###

# @name updatePerson
PUT http://localhost:5000/api/persons
Content-Type: application/json

{
    "id": "{{createPerson.response.body.$.id}}",
    "name": "James Garmush",
    "age": 31
}

###

# @name deletePerson
DELETE http://localhost:5000/api/persons/{{createPerson.response.body.$.id}}
Content-Type: application/json